Repository JoshPaulson1/SystemAdminLab, pull requests merged in 2019-10, with the labels that each got.

#1 Josh
  2file.notepad
  Josh.notepad
Labels: help wanted

#9 the lost dog
  lost-dog.html
Labels: enhancement

#8 four
  fourth.html
Labels: good first issue

#7 3
  third.html
Labels: documentation

#11 swimming
  POOL.html
Labels: bug

#10 big mac meal
  bigmac.html
Labels: bug

#16 Herman the German
  Herman.html
Labels: bug

#18 Peter
  Peter.html
Labels: documentation
